name: Bastila PR Check
description: Bastila searches your code for predefined outdated practices and standards, ensures you do not add anymore into your code, and tracks the progression of removing those old standards.

on:
  pull_request:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variable
        run: echo "BASTILA_KEY=${{ secrets.BASTILA_KEY }}" >> $BASTILA_KEY

      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run API request script
        run: python api_request.py
