name: 'Bastila PR Check'
description: 'Bastila searches your code for predefined outdated practices and standards'
branding:
  icon: 'git-pull-request'
  color: 'orange'

inputs:
  BASTILA_KEY:
    description: 'The API key for Bastila'
    required: true
  POST_RESULTS:
    description: 'Whether to post the progress to Bastila'
    required: false
    default: 'false'
  PREVENT_REGRESSION:
    description: 'Whether to prevent changes that add deprecated patterns'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
          
    - run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pathspec
      shell: bash

    - run: python ${{ github.action_path }}/search_files.py
      shell: bash
      env:
        BASTILA_KEY: ${{ inputs.BASTILA_KEY }}
        POST_RESULTS: ${{ inputs.POST_RESULTS }}
        PREVENT_REGRESSION: ${{ inputs.PREVENT_REGRESSION }}
