name: 'Bastila PR Check'
description: 'Bastila searches your code for predefined outdated practices and standards'
branding:
  icon: 'git-pull-request'
  color: 'orange'
inputs:
  BASTILA_KEY:
    description: 'The API key for Bastila'
    required: true
runs:
  using: 'composite'  # to enable running multiple shell commands
  steps:
    - run: echo "BASTILA_KEY=${{ inputs.BASTILA_KEY }}" >> $GITHUB_ENV
      shell: bash

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
          
    - run: |
        python -m pip install --upgrade pip
        pip install requests
      shell: bash

    - run: python api_request.py
      shell: bash
