name: Search Files

on:
  pull_request:
    branches:
      - '**'

jobs:
  search_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install dependencies
        run: go mod download

      - name: Search files
        run: go run search_files.go
