name: Search Repository

on:
  pull_request:
    branches:
    - main

jobs:
  search:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install PyGithub

    - name: Run Python script
      run: python search-repository.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_HEAD_SHA: ${{ github.sha }}
        GITHUB_REPOSITORY: ${{ github.repository }}
