name: PR API Request

on:
  pull_request:
    branches:
      - main

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run API request script
        run: python api_request.py
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          COMPARE_BRANCH: ${{ github.head_ref }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}